# Generated by Django 4.2.27 on 2026-02-02 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
