# Generated by Django 4.2.27 on 2026-02-02 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_article_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sub_category_names',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
