FROM apache/airflow:2.7.1

USER root
RUN apt-get update && apt-get install -y gcc python3-dev libpq-dev

USER airflow
RUN pip install --no-cache-dir \
    django \
    django-allauth \
    django-environ \
    psycopg2-binary \
    google-generativeai \
    requests \
    beautifulsoup4 \
    feedparser \
    newspaper3k \
    lxml