services:
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=custom_economy
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password1234

  django-app:
    image: xihxxn/custom-economy:latest
    user: root  # 권한 에러 방지
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_NAME=custom_economy
      - DB_USER=postgres
      - DB_PASSWORD=password1234
      - ALLOWED_HOSTS=* # 모든 접속 허용 (에러 해결 핵심)
    volumes:
      - static_volume:/app/staticfiles
      - .:/app  # 현재 폴더의 소스코드와 DAG를 컨테이너에 연결 (DAG 해결 핵심)

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
    depends_on:
      - django-app

  airflow-webserver:
    image: xihxxn/custom-economy:latest
    user: root
    command: airflow standalone
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=postgres
      - DB_NAME=custom_economy
      - DB_USER=postgres
      - DB_PASSWORD=password1234
      - AIRFLOW__CORE__DAGS_FOLDER=/app/dags
      - AIRFLOW__CORE__LOAD_EXAMPLES=False  # 예제 DAG 숨기기
      - AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_ALL_ADMINS=True
    volumes:
      - .:/app  # 내 DAG 파일을 인식시키기 위해 연결

volumes:
  postgres_data:
  static_volume: