services:

  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d myproject_db"]
      interval: 5s
      timeout: 5s
      retries: 5


  django-app:
    image: xihxxn/custom-economy:latest
    command: >
      sh -c "
      mkdir -p /app/staticfiles &&
      python manage.py collectstatic --noinput &&
      python manage.py migrate --noinput &&
      gunicorn --bind 0.0.0.0:8000 config.wsgi:application"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DOCKER_ENV: "1"
    volumes:
      - static_volume:/app/staticfiles


  airflow:
    image: apache/airflow:3.1.7
    env_file:
      - .env
    environment:
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://${DB_USER}:${DB_PASSWORD}@postgres/${DB_NAME}
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_SECRET_KEY}
      AIRFLOW__CORE__SIMPLE_AUTH_MANAGER_USERS: admin:admin
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
    command: >
      bash -c "
      airflow db migrate &&
      airflow standalone"


  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static_volume:/app/staticfiles
    depends_on:
      - django-app


volumes:
  postgres_data:
  static_volume:
