# Generated by Django 4.2.27 on 2026-02-14 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleExplanation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(help_text='1~5')),
                ('article_explanation', models.TextField()),
                ('term_explanation', models.TextField()),
                ('prediction', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
        migrations.CreateModel(
            name='InterestBasedPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest', models.CharField(choices=[('대출/금융', '대출/금융'), ('부동산', '부동산'), ('투자', '투자'), ('소비', '소비'), ('취업/고용', '취업/고용'), ('자영업/사업자', '자영업/사업자'), ('세금/정책', '세금/정책'), ('환율/해외', '환율/해외')], max_length=20)),
                ('prediction_text', models.TextField(verbose_name='관심분야 전망')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('explanation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_predictions', to='explanations.articleexplanation')),
            ],
            options={
                'verbose_name': '관심사별 전망',
                'unique_together': {('explanation', 'interest')},
            },
        ),
    ]
