# Generated by Django 4.2.27 on 2026-01-29 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleExplanation',
            fields=[
                ('explanation_id', models.AutoField(primary_key=True, serialize=False)),
                ('level', models.IntegerField()),
                ('background_text', models.TextField()),
                ('detail_text', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.article')),
            ],
        ),
    ]
