# Generated by Django 4.2.27 on 2026-02-10 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nickname',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='job',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
