server {
    listen 80;
    server_name customeconomy.duckdns.org;

    location / {
        proxy_pass http://django-app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    location /media/ {
        alias /app/media/;  # 도커 컨테이너 내부의 media 폴더 경로
        expires 30d;        # 이미지 캐싱 (선택사항)
        add_header Cache-Control "public";
    }
    # 정적 파일 경로 (정석)
    location /static/ {
        alias /app/staticfiles/;
    }
}