# Generated by Django 4.2.27 on 2026-02-14 03:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("quizzes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizresult",
            name="selected_answer",
            field=models.TextField(),
        ),
    ]
