# Generated by Django 4.2.27 on 2026-02-03 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='interest',
            field=models.ForeignKey(blank=True, help_text='18개 소분류 (약점 분석용)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='accounts.interest'),
        ),
    ]
